kubectl get nodes -o json | jq '.items[].spec.taints'
kubectl taint nodes --all node-role.kubernetes.io/master-
kubectl get nodes --show-labels |grep node-role
kubectl get po -o wide





apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  labels:
    role: myrole
spec:
  containers:
    - name: static-busybox
      image: busybox
      args: [ "sleep","1000" ]
  nodeSelector: 
    kubernetes.io/role: master
