apiVersion: v1
kind: Pod
metadata:
  name: nginx-critical
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: ip-172-31-6-54.eu-west-1.compute.internal
  restartPolicy: OnFailure
