apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  labels:
    role: myrole
spec:
  containers:
    - name: static-busybox
      image: busybox
      args: [ "sleep","1000" ]
  nodeSelector: 
    kubernetes.io/role: master
